### PR TITLE
update to cmake build

### PR DESCRIPTION
**Pull request by markschatza**
Here you go! :)

* I would test this before merging. Not sure how to test its actually working. But it builds fine on my machine.

### CODE REVIEW

**Comment by alejoe91** [comment]
Thank you so much! I'll test on linux and mac (no windows machine available here). Have you tested it on windows by any chance?

**Comment by markschatza** [comment]
I loaded it into my signal chain with no issues. Not sure how to test beyond that.

**Comment by alejoe91** [comment]
On Windows? :)

**Comment by markschatza** [comment]
Yep!

**Pull request merged**
